name: Monitor
on:
  schedule:
    - cron: "*/5 * * * *"  # هر ۵ دقیقه اجرا می‌شود
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install node-fetch
      - run: node check.js
      - run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add status.json
          git commit -m "Update status"
          git push
